
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { QuestionRow } from '@/lib/supabase-types';

const SUPABASE_URL = "https://lbyxtryvvjcqgqscwbiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxieXh0cnl2dmpjcWdxc2N3Yml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTM0MjEsImV4cCI6MjA1ODQ2OTQyMX0.kfxX0gW8_ARcTI6IbeBv9c7o7m5Rlv43WaDniCPKEgo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Type augmentation to help TypeScript recognize our tables
type CustomDatabase = Database & {
  public: {
    Tables: {
      questions: {
        Row: QuestionRow;
        Insert: Omit<QuestionRow, 'id' | 'created_at'>;
        Update: Partial<Omit<QuestionRow, 'id' | 'created_at'>>;
      };
    };
  };
};

export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
